// Generated by CoffeeScript 1.6.2
(function() {
  chrome.runtime.onMessage.addListener(function(req, sender, sendResponse) {
    if (req["init_script"]) {
      chrome.browserAction.setBadgeText({
        text: 'WAIT'
      });
      return chrome.browserAction.setBadgeBackgroundColor({
        color: [0, 0, 255, 255]
      });
    } else if (req["has_leap"] && req["has_leap"] === true) {
      chrome.browserAction.setBadgeBackgroundColor({
        color: [0, 255, 0, 255]
      });
      return chrome.browserAction.setBadgeText({
        text: 'OK'
      });
    } else if (req["has_leap"] && req["has_leap"] === false) {
      chrome.browserAction.setBadgeText({
        text: 'OFF'
      });
      return chrome.browserAction.setBadgeBackgroundColor({
        color: [255, 0, 0, 255]
      });
    }
  });

}).call(this);
